[global]
developmentMode = false

[server]
headless = true
runOnSave = false
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"
showSidebarNavigation = false

[theme]
base = "light"
primaryColor = "#0E7C86"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F8FA"
textColor = "#10151F"
